### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aadilsaif**

### CODE REVIEW

**Comment by opendatasets1** [comment]
Aadil, If I am looking in the right place the name of the College should be
College of Information. Not College of Information Science. I don;t see
that change yet...

**Comment by aadilsaif** [comment]
@opendatasets1 Ahh you're right. Sorry just fixed that.

**Comment by opendatasets1** [comment]
looks fine now, I don't see where to approve so you can go ahead and
release it.

**Comment by opendatasets1** [comment]
sorry I just looked again there is still one reference with the work
Science, the college is referenced twice.

**Comment by aadilsaif** [comment]
Fixed. You can approve the request by hitting the approve button at the bottom of the page where you would add a comment. In the dropdown instead of commenting you can approve.

**Comment by aadilsaif** [comment]
Or you can go to the Files Changed tab and hit the dropdown that says review changes and approve using that

**Comment by aadilsaif** [comment]
Screenshot 2024-12-18 at 8 57 11 AM

**Comment by opendatasets1** [comment]
[image: image.png]



[image: image.png]

**Comment by opendatasets1** [comment]
Don't see an ap[prove option in either place... can you show me where it is
supposed to be?

**Comment by opendatasets1** [comment]
im looking...

**Comment by aadilsaif** [comment]
Can you reattach the screenshots you sent, neither are visible

**Comment by opendatasets1** [comment]
what do I clickon  to get that drop down?

**Comment by aadilsaif** [comment]
The green review changes button, under the Files Changed tab

**Comment by opendatasets1** [comment]
i see that in the screen shot but I don;t have those options so far
[image: image.png]

**Comment by opendatasets1** [comment]
other screenshots

**Review by opendatasets1 — APPROVED** [review]

**Comment by opendatasets1** [comment]
ok I found it don;t ask me how.. see if it's approved.

**Comment by aadilsaif** [comment]
Yep, its been merged, changes should be reflected on the website soon. If you dont see it just refresh the page a couple times.

**Comment by opendatasets1** [comment]
Fixed!
[image: image.png]

**Comment by opendatasets1** [comment]
I have a lot to learn about github🌞 Thanks so much for your patience.

**Pull request merged**
